---
name: Release

# Lifted shamelessly from https://github.com/custom-components/grocy

on:
  release:
    types: [published]

permissions: {}

jobs:
  release_zip_file:
    name: Prepare and upload release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BERMUDA_ROOT_DIR: "${{ github.workspace }}/custom_components/bermuda"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set release version number in files
        run: |
          sed -i '/VERSION.=./c\VERSION = "${{ github.ref_name }}"' "${{ env.BERMUDA_ROOT_DIR }}/const.py"
          (jq '.version = "${{ github.ref_name }}"' "${{ env.BERMUDA_ROOT_DIR }}/manifest.json") > "${{ env.BERMUDA_ROOT_DIR }}/manifest.json.tmp"
          mv "${{ env.BERMUDA_ROOT_DIR }}/manifest.json.tmp" "${{ env.BERMUDA_ROOT_DIR }}/manifest.json"

      - name: Zip the integration directory
        run: |
          cd "${{ env.BERMUDA_ROOT_DIR }}"
          zip bermuda.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ env.BERMUDA_ROOT_DIR }}/bermuda.zip
